//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectReseller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageItemsView
    {
        public int id { get; set; }
        public int users_id { get; set; }
        public int category_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> sold { get; set; }
        public string users_name { get; set; }
        public string city { get; set; }
    }
}
