//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectReseller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int id { get; set; }
        public int users_id { get; set; }
        public int item_category_id { get; set; }
        public int item_users_id { get; set; }
        public int item_id { get; set; }
        public string content { get; set; }
        public Nullable<bool> verified { get; set; }
    
        public virtual item item { get; set; }
        public virtual users users { get; set; }
    }
}
