//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectReseller.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.delivery = new HashSet<delivery>();
            this.item = new HashSet<item>();
            this.message = new HashSet<message>();
            this.message_recipient = new HashSet<message_recipient>();
            this.report = new HashSet<report>();
        }
    
        public int id { get; set; }
        [DisplayName("Nazwa")]
        public string name { get; set; }
        [DisplayName("Has³o")]
        public string password { get; set; }
        [DisplayName("Miasto")]
        public string city { get; set; }
        [DisplayName("Kod pocztowy")]
        public string postcode { get; set; }
        [DisplayName("Numer telefonu")]
        public string phone { get; set; }
        [DisplayName("Typ konta")]
        public Nullable<int> account_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery> delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message_recipient> message_recipient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> report { get; set; }
    }
}
